{"identifier":{"url":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/AddingButtons","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Configuration","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Destinations","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/GettingStarted","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/KeyConcepts","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Requisites","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Scanner","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Static-Maps","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Subscriptions"],"generated":true,"title":"Articles"},{"title":"Classes","identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/HeatMap","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitActionButtonItem","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitSDK","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitSubscriptionToken","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenue"]},{"identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Context","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/DestinationProtocol","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/EventFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/EventTrigger","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoView","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewButton","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewIcon","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewLabel","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelSwitcher","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LocalVenue","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LocalVenueRegion","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RecenterButton","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitBarcodeDelegate","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitInterfaceControls","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLayout","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitListDelegate","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocationDelegate","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitMapDelegate","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitRequisitesDelegate","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewController","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SubscriptionEvent","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/UnixTimestampedMetadata","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Venue","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManager","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueMetadata"],"title":"Protocols"},{"identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ConfigurationKey","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/DestinationAdditionalInfoKey","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/HeatMapEvent","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewModelFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelTransition","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RoutingOptions","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ScanResult","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitContextFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitDestination","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocalVenue","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocalVenueRegion","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenueMetadata","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewControllerFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/StaticMapViewControllerFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Theme","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManagerConfiguration","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManagerFactory"],"title":"Structures"},{"identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Destination","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelSwitcherFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RecenterButtonFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitImage","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpacekitVenueManagerError-swift.typealias"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Event","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/MapAnnotationState","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Requisite","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RoutingFailure","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitActionButtonFactory","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitButtonStack","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitButtonStackInsertionPoint","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenueManagerError-swift.enum","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewKey","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/TraversalOption"]},{"title":"Extended Modules","identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ARKit","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Swift","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/UIKit"]}],"sections":[],"hierarchy":{"paths":[[]]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"inlineContent":[{"type":"text","text":"SpaceKit provides advanced indoor positioning, maps, navigation and augmented reality directions in an easy-to-implement framework for iOS applications to take advantage of."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"It comprises of 4 key layers in a stack that make up our framework. Each layer builds upon the other, with HyperLocation being the foundation upon which all the other layers are built apon."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"framework-components-diagram"}]},{"level":3,"type":"heading","anchor":"HyperLocation","text":"HyperLocation"},{"inlineContent":[{"type":"text","text":"Other location technology don’t work well indoors. GPS requires a  line-of-sight from a number of overhead satellites to triangulate a position. In a typical indoor scenario, concrete, metal structures and power cables prevent GPS signals reaching a user’s mobile device while Bluetooth iBeacons aren’t very accurate and require regular monitoring to ensure their batteries haven’t failed or that they haven’t been moved."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Instead, with HyperLocation, we’ve built it with location in mind from the start. We use a wide variety of device sensors, camera data and previously-surveyed Wi-Fi data fed into our finely-tuned ML models and algorithms to provide "},{"inlineContent":[{"type":"text","text":"HyperAccurate"}],"type":"emphasis"},{"type":"text","text":" location information indoors to sub-1m accuracy."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/www.hyperar.com\/features\/location","type":"reference","isActive":true}]}]}]},{"level":3,"anchor":"Indoor-Maps","type":"heading","text":"Indoor Maps"},{"type":"paragraph","inlineContent":[{"text":"Another key part of our technology are our detailed indoor maps. These rich maps are the backbone to the ","type":"text"},{"inlineContent":[{"type":"text","text":"Hyper Experience"}],"type":"emphasis"},{"text":". Typically created in our online Hyper Map Creator “portal”, these maps contain a complete digital twin of a retail environment from walls, sections, floors all the way down to individual fixtures and till points which we render as a 3D map and use to help calculate navigation routes.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/www.hyperar.com\/features\/maps","type":"reference","isActive":true}]}]}],"type":"unorderedList"},{"type":"heading","text":"Navigation Routing","level":3,"anchor":"Navigation-Routing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In addition to our rich highly-detailed maps and advanced location technology, is our navigation technology. We use these components to create dynamic route plans that help customers find your products quicker and faster than they could on their own."}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/www.hyperar.com\/features\/navigation","isActive":true}]}]}],"type":"unorderedList"},{"text":"Augmented Reality","level":3,"type":"heading","anchor":"Augmented-Reality"},{"type":"paragraph","inlineContent":[{"text":"Once a customer has a route set, they can switch to Augmented Reality directions. This combines HyperLocation, a lively dynamic arrow and text directions which are then overlayed over a camera interface to provide an easy map-free way of finding an item.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/www.hyperar.com\/features\/reality","isActive":true,"type":"reference"}]}]}],"type":"unorderedList"},{"anchor":"Essentials","text":"Essentials","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/KeyConcepts"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/GettingStarted","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Configuration","isActive":true}]}]}]},{"type":"heading","anchor":"Customisation","level":2,"text":"Customisation"},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/AddingButtons","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"abstract":[{"text":"Indoor location that actually works!","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/spacekit"]},{"paths":["\/documentation\/spacekit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"collection","externalID":"SpaceKit","roleHeading":"Framework","color":{"standardColorIdentifier":"blue"},"title":"SpaceKit","symbolKind":"module","images":[{"identifier":"hyper-wireframe-icon.png","type":"icon"}],"modules":[{"name":"SpaceKit"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DentReality.SpaceKit/documentation/SpaceKit/UnixTimestampedMetadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UnixTimestampedMetadata"}],"abstract":[],"title":"UnixTimestampedMetadata","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnixTimestampedMetadata","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/spacekit\/unixtimestampedmetadata","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/UnixTimestampedMetadata"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Context":{"abstract":[{"type":"text","text":"Top-level object for communicating with SpaceKit."}],"title":"Context","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Context"}],"url":"\/documentation\/spacekit\/context","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Context","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Context","kind":"identifier"}],"kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitVenue":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SpaceKitVenue","kind":"identifier"}],"url":"\/documentation\/spacekit\/spacekitvenue","navigatorTitle":[{"kind":"identifier","text":"SpaceKitVenue"}],"type":"topic","role":"symbol","title":"SpaceKitVenue","abstract":[{"text":"An opaque container for SpaceKit venue data.","type":"text"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenue","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/VenueManager":{"navigatorTitle":[{"kind":"identifier","text":"VenueManager"}],"title":"VenueManager","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManager","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VenueManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/spacekit\/venuemanager","abstract":[{"text":"Used for communication with Hyper web portal to fetch and update local HMDF content.","type":"text"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/Requisite":{"role":"symbol","navigatorTitle":[{"text":"Requisite","kind":"identifier"}],"abstract":[{"text":"System-level capabilities required by the SpaceKit SDK.","type":"text"}],"title":"Requisite","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Requisite"}],"kind":"symbol","url":"\/documentation\/spacekit\/requisite","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Requisite"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Destinations":{"role":"collectionGroup","abstract":[{"type":"text","text":"The destinations API is used to manage navigation in SpaceKit."}],"title":"Destinations","type":"topic","kind":"article","url":"\/documentation\/spacekit\/destinations","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Destinations"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Requisites":{"url":"\/documentation\/spacekit\/requisites","abstract":[{"type":"text","text":"The requisites API can be used to determine the status of required system-level permissions."}],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Requisites","title":"Requisites"},"doc://DentReality.SpaceKit/documentation/SpaceKit/StaticMapViewControllerFactory":{"role":"symbol","navigatorTitle":[{"text":"StaticMapViewControllerFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"A factory for initialising a static map view controller, centered on a destination."}],"title":"StaticMapViewControllerFactory","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticMapViewControllerFactory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/spacekit\/staticmapviewcontrollerfactory","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/StaticMapViewControllerFactory"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitViewKey":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SpaceKitViewKey","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewKey","kind":"symbol","url":"\/documentation\/spacekit\/spacekitviewkey","title":"SpaceKitViewKey","abstract":[{"text":"An enum that defines keys for referencing views during layout.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpaceKitViewKey"}],"role":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitInterfaceControls":{"abstract":[],"url":"\/documentation\/spacekit\/spacekitinterfacecontrols","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SpaceKitInterfaceControls","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitInterfaceControls","kind":"symbol","navigatorTitle":[{"text":"SpaceKitInterfaceControls","kind":"identifier"}],"title":"SpaceKitInterfaceControls"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitDestination":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SpaceKitDestination","kind":"identifier"}],"navigatorTitle":[{"text":"SpaceKitDestination","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitDestination","abstract":[{"text":"A destination within the SpaceKit navigation system.","type":"text"}],"type":"topic","title":"SpaceKitDestination","url":"\/documentation\/spacekit\/spacekitdestination","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/TraversalOption":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TraversalOption"}],"abstract":[],"title":"TraversalOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TraversalOption","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/spacekit\/traversaloption","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/TraversalOption"},"doc://DentReality.SpaceKit/documentation/SpaceKit/LocalVenue":{"role":"symbol","navigatorTitle":[{"text":"LocalVenue","kind":"identifier"}],"abstract":[{"text":"Local venue returned by","type":"text"},{"type":"codeVoice","code":"VenueManager.fetchLocalVenues(...)"}],"title":"LocalVenue","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocalVenue","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/spacekit\/localvenue","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LocalVenue"},"doc://DentReality.SpaceKit/documentation/SpaceKit/GettingStarted":{"role":"article","abstract":[{"text":"Discover the fundimental process behind building and displaying a map.","type":"text"}],"images":[{"type":"icon","identifier":"hyper-wireframe-icon.png"}],"title":"Getting Started","type":"topic","kind":"article","url":"\/documentation\/spacekit\/gettingstarted","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/GettingStarted"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Event":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Event","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"title":"Event","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Event"}],"url":"\/documentation\/spacekit\/event"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitImage":{"role":"symbol","navigatorTitle":[{"text":"SpaceKitImage","kind":"identifier"}],"abstract":[],"title":"SpaceKitImage","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SpaceKitImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/spacekit\/spacekitimage","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitImage"},"doc://DentReality.SpaceKit/documentation/SpaceKit":{"url":"\/documentation\/spacekit","type":"topic","role":"collection","title":"SpaceKit","abstract":[{"type":"text","text":"Indoor location that actually works!"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit","kind":"symbol","images":[{"identifier":"hyper-wireframe-icon.png","type":"icon"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/DestinationProtocol":{"title":"DestinationProtocol","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/DestinationProtocol","abstract":[],"url":"\/documentation\/spacekit\/destinationprotocol","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DestinationProtocol"}],"navigatorTitle":[{"text":"DestinationProtocol","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/ScanResult":{"abstract":[{"text":"A barcode scan completed within SpaceKit.","type":"text"}],"title":"ScanResult","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ScanResult"}],"url":"\/documentation\/spacekit\/scanresult","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ScanResult","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanResult"}],"kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/VenueManagerFactory":{"title":"VenueManagerFactory","type":"topic","abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManagerFactory","url":"\/documentation\/spacekit\/venuemanagerfactory","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"VenueManagerFactory","kind":"identifier"}],"navigatorTitle":[{"text":"VenueManagerFactory","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/HeatMapEvent":{"title":"HeatMapEvent","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/HeatMapEvent","abstract":[{"text":"A record of a single heatmap data point event","type":"text"}],"url":"\/documentation\/spacekit\/heatmapevent","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeatMapEvent","kind":"identifier"}],"navigatorTitle":[{"text":"HeatMapEvent","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitActionButtonFactory":{"kind":"symbol","type":"topic","title":"SpaceKitActionButtonFactory","url":"\/documentation\/spacekit\/spacekitactionbuttonfactory","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SpaceKitActionButtonFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SpaceKitActionButtonFactory"}],"abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitActionButtonFactory"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SubscriptionEvent":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SubscriptionEvent","kind":"identifier"}],"navigatorTitle":[{"text":"SubscriptionEvent","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SubscriptionEvent","abstract":[{"text":"An event that can be subscribed to.","type":"text"}],"type":"topic","title":"SubscriptionEvent","url":"\/documentation\/spacekit\/subscriptionevent","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitVenueMetadata":{"abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenueMetadata","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SpaceKitVenueMetadata","kind":"identifier"}],"url":"\/documentation\/spacekit\/spacekitvenuemetadata","title":"SpaceKitVenueMetadata","navigatorTitle":[{"text":"SpaceKitVenueMetadata","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoViewButton":{"title":"InfoViewButton","type":"topic","abstract":[{"text":"A button that will be used in ","type":"text"},{"type":"codeVoice","code":"InfoView"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewButton","url":"\/documentation\/spacekit\/infoviewbutton","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"InfoViewButton","kind":"identifier"}],"navigatorTitle":[{"text":"InfoViewButton","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitLocationDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitLocationDelegate"}],"abstract":[{"type":"text","text":"Delegate used for location-related communication with SpaceKit."}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocationDelegate","title":"SpaceKitLocationDelegate","navigatorTitle":[{"kind":"identifier","text":"SpaceKitLocationDelegate"}],"role":"symbol","deprecated":true,"kind":"symbol","url":"\/documentation\/spacekit\/spacekitlocationdelegate"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitActionButtonItem":{"abstract":[{"text":"A button that triggers an action for use inside the primary user interface for SpaceKit.","type":"text"}],"url":"\/documentation\/spacekit\/spacekitactionbuttonitem","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitActionButtonItem"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitActionButtonItem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SpaceKitActionButtonItem"}],"title":"SpaceKitActionButtonItem"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitMapDelegate":{"title":"SpaceKitMapDelegate","url":"\/documentation\/spacekit\/spacekitmapdelegate","abstract":[{"type":"text","text":"Delegate for callbacks relating to the map feature"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitMapDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceKitMapDelegate"}],"navigatorTitle":[{"text":"SpaceKitMapDelegate","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitLocalVenue":{"title":"SpaceKitLocalVenue","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocalVenue","abstract":[],"url":"\/documentation\/spacekit\/spacekitlocalvenue","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpaceKitLocalVenue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SpaceKitLocalVenue"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitSDK":{"title":"SpaceKitSDK","type":"topic","abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitSDK","url":"\/documentation\/spacekit\/spacekitsdk","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SpaceKitSDK","kind":"identifier"}],"navigatorTitle":[{"text":"SpaceKitSDK","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/EventTrigger":{"kind":"symbol","role":"symbol","url":"\/documentation\/spacekit\/eventtrigger","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/EventTrigger","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EventTrigger","kind":"identifier"}],"abstract":[{"text":"Criteria to be used when evaluating a ","type":"text"},{"code":"SubscriptionEvent","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EventTrigger"}],"title":"EventTrigger","type":"topic"},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoView":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InfoView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"InfoView"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoView","abstract":[{"type":"text","text":"Implementations of "},{"type":"codeVoice","code":"InfoView"},{"type":"text","text":" can be used to display custom UI content for display in the reserved area of the SpaceKit view."}],"type":"topic","title":"InfoView","url":"\/documentation\/spacekit\/infoview","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/EventFactory":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventFactory","kind":"identifier"}],"navigatorTitle":[{"text":"EventFactory","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/EventFactory","abstract":[{"text":"Used to create ","type":"text"},{"type":"codeVoice","code":"SubscriptionEvents"},{"text":" within the context of a SpaceKit instance.","type":"text"}],"type":"topic","title":"EventFactory","url":"\/documentation\/spacekit\/eventfactory","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/AddingButtons":{"kind":"article","role":"article","images":[{"identifier":"hyper-wireframe-icon.png","type":"icon"}],"abstract":[{"text":"A quick overview of how to add custom UI to a SpaceKit map.","type":"text"}],"type":"topic","url":"\/documentation\/spacekit\/addingbuttons","title":"Adding Buttons and Actions","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/AddingButtons"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Swift":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/spacekit\/swift","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Swift","abstract":[],"title":"Swift"},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoViewModelFactory":{"title":"InfoViewModelFactory","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewModelFactory","abstract":[],"url":"\/documentation\/spacekit\/infoviewmodelfactory","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InfoViewModelFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"InfoViewModelFactory"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitContextFactory":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SpaceKitContextFactory"}],"abstract":[],"title":"SpaceKitContextFactory","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitContextFactory"}],"type":"topic","url":"\/documentation\/spacekit\/spacekitcontextfactory","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitContextFactory","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Destination":{"deprecated":true,"title":"Destination","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Destination","abstract":[],"url":"\/documentation\/spacekit\/destination","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Destination","kind":"identifier"}],"navigatorTitle":[{"text":"Destination","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/LocalVenueRegion":{"type":"topic","title":"LocalVenueRegion","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LocalVenueRegion","abstract":[{"type":"text","text":"Circular area described using center point and radius."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalVenueRegion"}],"url":"\/documentation\/spacekit\/localvenueregion","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalVenueRegion","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/MapAnnotationState":{"type":"topic","title":"MapAnnotationState","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/MapAnnotationState","navigatorTitle":[{"kind":"identifier","text":"MapAnnotationState"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MapAnnotationState","kind":"identifier"}],"url":"\/documentation\/spacekit\/mapannotationstate","role":"symbol","kind":"symbol","abstract":[{"text":"State for an annotation on the Map","type":"text"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/RecenterButton":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecenterButton","kind":"identifier"}],"url":"\/documentation\/spacekit\/recenterbutton","navigatorTitle":[{"kind":"identifier","text":"RecenterButton"}],"type":"topic","role":"symbol","title":"RecenterButton","abstract":[{"type":"text","text":"A control that recenters the map on the user’s current location."},{"type":"text","text":" "},{"text":"When the control’s primaryActionTriggered event is sent, the map will recenter.","type":"text"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RecenterButton","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/UIKit":{"title":"UIKit","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/UIKit","abstract":[],"url":"\/documentation\/spacekit\/uikit","kind":"symbol","role":"collection"},"doc://DentReality.SpaceKit/documentation/SpaceKit/ConfigurationKey":{"url":"\/documentation\/spacekit\/configurationkey","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ConfigurationKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConfigurationKey"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConfigurationKey"}],"title":"ConfigurationKey","type":"topic","role":"symbol","kind":"symbol"},"https://www.hyperar.com/features/reality":{"type":"link","url":"https:\/\/www.hyperar.com\/features\/reality","titleInlineContent":[{"text":"Augmented Reality Feature Details","type":"text"}],"title":"Augmented Reality Feature Details","identifier":"https:\/\/www.hyperar.com\/features\/reality"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitBarcodeDelegate":{"abstract":[{"text":"Delegate used for callbacks related to barcode scanning within SpaceKit.","type":"text"}],"type":"topic","title":"SpaceKitBarcodeDelegate","role":"symbol","navigatorTitle":[{"text":"SpaceKitBarcodeDelegate","kind":"identifier"}],"url":"\/documentation\/spacekit\/spacekitbarcodedelegate","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitBarcodeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitBarcodeDelegate"}],"kind":"symbol"},"framework-components-diagram":{"type":"image","identifier":"framework-components-diagram","variants":[{"traits":["3x","light"],"url":"\/images\/framework-components-diagram@3x.png"},{"url":"\/images\/framework-components-diagram~dark@3x.png","traits":["3x","dark"]}],"alt":"A diagram showing how HyperLocation, Indoor Maps, Navigation Routing and Augmented Reality build upon each other."},"doc://DentReality.SpaceKit/documentation/SpaceKit/DestinationAdditionalInfoKey":{"abstract":[{"text":"A structure that defines additional destination information keys.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"DestinationAdditionalInfoKey","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DestinationAdditionalInfoKey"}],"title":"DestinationAdditionalInfoKey","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/DestinationAdditionalInfoKey","url":"\/documentation\/spacekit\/destinationadditionalinfokey","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/RoutingOptions":{"title":"RoutingOptions","type":"topic","abstract":[{"text":"Options for SpaceKit to use when planning routes.","type":"text"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RoutingOptions","url":"\/documentation\/spacekit\/routingoptions","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RoutingOptions"}],"navigatorTitle":[{"text":"RoutingOptions","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/LevelSwitcher":{"title":"LevelSwitcher","abstract":[{"type":"text","text":"A control that allows the user to set the level displayed on the map."}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelSwitcher","type":"topic","url":"\/documentation\/spacekit\/levelswitcher","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LevelSwitcher","kind":"identifier"}],"navigatorTitle":[{"text":"LevelSwitcher","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitLocalVenueRegion":{"title":"SpaceKitLocalVenueRegion","type":"topic","kind":"symbol","url":"\/documentation\/spacekit\/spacekitlocalvenueregion","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLocalVenueRegion","navigatorTitle":[{"text":"SpaceKitLocalVenueRegion","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitLocalVenueRegion"}],"role":"symbol","abstract":[]},"doc://DentReality.SpaceKit/documentation/SpaceKit/Static-Maps":{"title":"Static Maps","type":"topic","abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Static-Maps","url":"\/documentation\/spacekit\/static-maps","kind":"article","role":"article"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitLayout":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitLayout"}],"kind":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitLayout","abstract":[{"type":"text","text":"A protocol for laying out SpaceKit views."}],"type":"topic","title":"SpaceKitLayout","url":"\/documentation\/spacekit\/spacekitlayout","navigatorTitle":[{"kind":"identifier","text":"SpaceKitLayout"}],"role":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitViewController":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpaceKitViewController","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewController","kind":"symbol","type":"topic","url":"\/documentation\/spacekit\/spacekitviewcontroller","title":"SpaceKitViewController","abstract":[{"text":"Primary user interface for SpaceKit navigation including map and AR.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SpaceKitViewController"}],"role":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/RoutingFailure":{"title":"RoutingFailure","abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RoutingFailure","type":"topic","url":"\/documentation\/spacekit\/routingfailure","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingFailure","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RoutingFailure"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/RecenterButtonFactory":{"title":"RecenterButtonFactory","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/RecenterButtonFactory","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecenterButtonFactory","kind":"identifier"}],"url":"\/documentation\/spacekit\/recenterbuttonfactory","navigatorTitle":[{"kind":"identifier","text":"RecenterButtonFactory"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitVersionNumber":{"title":"SpaceKitVersionNumber","type":"topic","abstract":[{"type":"text","text":"Project version number for SpaceKit."}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVersionNumber","url":"\/documentation\/spacekit\/spacekitversionnumber","kind":"symbol","role":"symbol","fragments":[{"text":"SpaceKitVersionNumber","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitButtonStackInsertionPoint":{"title":"SpaceKitButtonStackInsertionPoint","abstract":[{"text":"An enum that represents at which end the button will be inserted onto the button stack","type":"text"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitButtonStackInsertionPoint","type":"topic","url":"\/documentation\/spacekit\/spacekitbuttonstackinsertionpoint","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SpaceKitButtonStackInsertionPoint","kind":"identifier"}],"navigatorTitle":[{"text":"SpaceKitButtonStackInsertionPoint","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/VenueManagerConfiguration":{"navigatorTitle":[{"text":"VenueManagerConfiguration","kind":"identifier"}],"title":"VenueManagerConfiguration","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueManagerConfiguration","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/spacekit\/venuemanagerconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VenueManagerConfiguration"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/HeatMap":{"title":"HeatMap","type":"topic","abstract":[],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/HeatMap","url":"\/documentation\/spacekit\/heatmap","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeatMap"}],"navigatorTitle":[{"text":"HeatMap","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitVenueManagerError-swift.enum":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/spacekit\/spacekitvenuemanagererror-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitVenueManagerError"}],"title":"SpaceKitVenueManagerError","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVenueManagerError-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SpaceKitVenueManagerError"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/ARKit":{"kind":"symbol","role":"collection","abstract":[],"title":"ARKit","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/ARKit","url":"\/documentation\/spacekit\/arkit","type":"topic"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Configuration":{"abstract":[{"text":"Specify internal SpaceKit behaviours using a configuration file.","type":"text"}],"type":"topic","title":"Configuration","role":"article","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Configuration","url":"\/documentation\/spacekit\/configuration","kind":"article","images":[{"identifier":"hyper-wireframe-icon.png","type":"icon"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitListDelegate":{"abstract":[{"text":"Delegate used to communicate updates within the SpaceKit navigation system.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SpaceKitListDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitListDelegate"}],"title":"SpaceKitListDelegate","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitListDelegate","kind":"symbol","url":"\/documentation\/spacekit\/spacekitlistdelegate"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitRequisitesDelegate":{"abstract":[{"type":"text","text":"Delegate used for callbacks relating to SpaceKit’s system-level requirements."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpaceKitRequisitesDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpaceKitRequisitesDelegate","kind":"identifier"}],"title":"SpaceKitRequisitesDelegate","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitRequisitesDelegate","url":"\/documentation\/spacekit\/spacekitrequisitesdelegate","kind":"symbol","deprecated":true},"https://www.hyperar.com/features/location":{"identifier":"https:\/\/www.hyperar.com\/features\/location","titleInlineContent":[{"text":"HyperLocation Feature Details","type":"text"}],"type":"link","title":"HyperLocation Feature Details","url":"https:\/\/www.hyperar.com\/features\/location"},"doc://DentReality.SpaceKit/documentation/SpaceKit/VenueMetadata":{"title":"VenueMetadata","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/VenueMetadata","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"VenueMetadata","kind":"identifier"}],"url":"\/documentation\/spacekit\/venuemetadata","abstract":[{"type":"text","text":"Metadata for a published SpaceKit venue."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VenueMetadata"}],"type":"topic"},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoViewFactory":{"url":"\/documentation\/spacekit\/infoviewfactory","navigatorTitle":[{"text":"InfoViewFactory","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"InfoViewFactory","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewFactory","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InfoViewFactory"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/Theme":{"url":"\/documentation\/spacekit\/theme","navigatorTitle":[{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"Theme for user interface elements"}],"type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Theme","kind":"symbol","title":"Theme","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Theme","kind":"identifier"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/Subscriptions":{"abstract":[{"text":"The subscriptions API allows a host app to respond to relevant events occurring within SpaceKit.","type":"text"}],"type":"topic","title":"Subscriptions","role":"collectionGroup","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Subscriptions","url":"\/documentation\/spacekit\/subscriptions","kind":"article"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpacekitVenueManagerError-swift.typealias":{"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpacekitVenueManagerError-swift.typealias","url":"\/documentation\/spacekit\/spacekitvenuemanagererror-swift.typealias","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SpacekitVenueManagerError","kind":"identifier"}],"navigatorTitle":[{"text":"SpacekitVenueManagerError","kind":"identifier"}],"role":"symbol","title":"SpacekitVenueManagerError","deprecated":true,"kind":"symbol","type":"topic"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitButtonStack":{"abstract":[{"text":"An enum that represents an area on the UI for placing additional","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpaceKitButtonStack"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitButtonStack"}],"title":"SpaceKitButtonStack","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitButtonStack","kind":"symbol","url":"\/documentation\/spacekit\/spacekitbuttonstack"},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoViewIcon":{"navigatorTitle":[{"kind":"identifier","text":"InfoViewIcon"}],"url":"\/documentation\/spacekit\/infoviewicon","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoViewIcon"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewIcon","kind":"symbol","title":"InfoViewIcon","abstract":[{"text":"An image that will appear as an icon in ","type":"text"},{"type":"codeVoice","code":"InfoView"}]},"hyper-wireframe-icon.png":{"alt":"The Hyper logo","identifier":"hyper-wireframe-icon.png","variants":[{"url":"\/images\/hyper-wireframe-icon.png","traits":["1x","light"]}],"type":"image"},"https://www.hyperar.com/features/maps":{"identifier":"https:\/\/www.hyperar.com\/features\/maps","titleInlineContent":[{"text":"Indoor Maps Feature Details","type":"text"}],"type":"link","title":"Indoor Maps Feature Details","url":"https:\/\/www.hyperar.com\/features\/maps"},"doc://DentReality.SpaceKit/documentation/SpaceKit/LevelSwitcherFactory":{"abstract":[{"text":"A closure that creates a Level Switcher control, given an array of all available level ordinals","type":"text"}],"type":"topic","navigatorTitle":[{"text":"LevelSwitcherFactory","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LevelSwitcherFactory"}],"title":"LevelSwitcherFactory","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelSwitcherFactory","url":"\/documentation\/spacekit\/levelswitcherfactory","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitViewControllerFactory":{"title":"SpaceKitViewControllerFactory","url":"\/documentation\/spacekit\/spacekitviewcontrollerfactory","abstract":[{"text":"A factory for initialising the primary SpaceKit navigation experience view controller.","type":"text"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitViewControllerFactory","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceKitViewControllerFactory"}],"navigatorTitle":[{"text":"SpaceKitViewControllerFactory","kind":"identifier"}],"type":"topic"},"https://www.hyperar.com/features/navigation":{"identifier":"https:\/\/www.hyperar.com\/features\/navigation","titleInlineContent":[{"type":"text","text":"Navigation Routing Feature Details"}],"type":"link","title":"Navigation Routing Feature Details","url":"https:\/\/www.hyperar.com\/features\/navigation"},"doc://DentReality.SpaceKit/documentation/SpaceKit/Scanner":{"abstract":[{"type":"text","text":"The scanner API can be used to handle input from SpaceKit’s integrated barcode scanner."}],"type":"topic","title":"Scanner","role":"collectionGroup","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Scanner","url":"\/documentation\/spacekit\/scanner","kind":"article"},"doc://DentReality.SpaceKit/documentation/SpaceKit/InfoViewLabel":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InfoViewLabel"}],"navigatorTitle":[{"text":"InfoViewLabel","kind":"identifier"}],"identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/InfoViewLabel","abstract":[{"type":"text","text":"A label that will appear in "},{"code":"InfoView","type":"codeVoice"}],"type":"topic","title":"InfoViewLabel","url":"\/documentation\/spacekit\/infoviewlabel","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitSubscriptionToken":{"kind":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitSubscriptionToken","role":"symbol","title":"SpaceKitSubscriptionToken","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SpaceKitSubscriptionToken"}],"navigatorTitle":[{"kind":"identifier","text":"SpaceKitSubscriptionToken"}],"url":"\/documentation\/spacekit\/spacekitsubscriptiontoken","abstract":[{"type":"text","text":"A token representing a subscription to an event within SpaceKit. The token may be retained and used to cancel its associated subscription."}],"type":"topic"},"doc://DentReality.SpaceKit/documentation/SpaceKit/KeyConcepts":{"abstract":[{"type":"text","text":"To help explain the key concepts of the SDK, we’ll use an example of a fictional hardware retail company called "},{"inlineContent":[{"type":"text","text":"ToolTime"}],"type":"emphasis"},{"text":" that sells DIY equipment and materials in their three retail spaces found in London, Manchester and Bristol.","type":"text"}],"type":"topic","title":"Key Concepts","role":"article","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/KeyConcepts","kind":"article","url":"\/documentation\/spacekit\/keyconcepts","images":[{"identifier":"hyper-wireframe-icon.png","type":"icon"}]},"doc://DentReality.SpaceKit/documentation/SpaceKit/Venue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Venue","kind":"identifier"}],"url":"\/documentation\/spacekit\/venue","navigatorTitle":[{"kind":"identifier","text":"Venue"}],"type":"topic","role":"symbol","title":"Venue","abstract":[{"text":"Opaque container for venue data.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Venue"},"doc://DentReality.SpaceKit/documentation/SpaceKit/LevelTransition":{"abstract":[{"text":"A container for information about a transition from one level to another on an ordered route","type":"text"}],"type":"topic","navigatorTitle":[{"text":"LevelTransition","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LevelTransition"}],"title":"LevelTransition","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/LevelTransition","url":"\/documentation\/spacekit\/leveltransition","kind":"symbol"},"doc://DentReality.SpaceKit/documentation/SpaceKit/SpaceKitVersionString":{"abstract":[{"type":"text","text":"Project version string for SpaceKit."}],"type":"topic","fragments":[{"text":"SpaceKitVersionString","kind":"identifier"}],"title":"SpaceKitVersionString","role":"symbol","identifier":"doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVersionString","kind":"symbol","url":"\/documentation\/spacekit\/spacekitversionstring"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/AddingButtons","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Configuration","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Destinations","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/GettingStarted","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/KeyConcepts","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Requisites","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Scanner","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Static-Maps","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/Subscriptions"],"generated":true},{"title":"Variables","identifiers":["doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVersionNumber","doc:\/\/DentReality.SpaceKit\/documentation\/SpaceKit\/SpaceKitVersionString"]}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}